import { StyleSheet } from 'react-native';

export const deliveryStyles = StyleSheet.create({
    container: {
        flex: 1,
    },
    safeArea: {
        flex: 1,
        backgroundColor: 'white',
    },
    mapArea: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        position: 'relative',
    },
    backButton: {
        position: 'absolute',
        top: 60,
        left: 24,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    locationButton: {
        position: 'absolute',
        top: 60,
        right: 24,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    mapContainer: {
        flex: 1,
        backgroundColor: '#F8F8F8',
        position: 'relative',
    },
    streetGrid: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    verticalLine: {
        position: 'absolute',
        width: 1,
        height: '100%',
        backgroundColor: '#E0E0E0',
    },
    horizontalLine: {
        position: 'absolute',
        height: 1,
        width: '100%',
        backgroundColor: '#E0E0E0',
    },
    routePath1: {
        position: 'absolute',
        top: '25%',
        left: '15%',
        width: '45%',
        height: 3,
        backgroundColor: '#C67C4E',
        borderRadius: 2,
    },
    routePath2: {
        position: 'absolute',
        top: '25%',
        left: '60%',
        width: 3,
        height: '35%',
        backgroundColor: '#C67C4E',
        borderRadius: 2,
    },
    routePath3: {
        position: 'absolute',
        top: '60%',
        left: '60%',
        width: '25%',
        height: 3,
        backgroundColor: '#C67C4E',
        borderRadius: 2,
    },
    deliveryPerson: {
        position: 'absolute',
        top: '23%',
        left: '13%',
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#C67C4E',
        alignItems: 'center',
        justifyContent: 'center',
    },
    destination: {
        position: 'absolute',
        top: '58%',
        right: '13%',
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#C67C4E',
        alignItems: 'center',
        justifyContent: 'center',
    },
    streetLabel1: {
        position: 'absolute',
        top: '35%',
        left: '5%',
        fontSize: 12,
        fontFamily: 'Sora_400Regular',
        color: '#9CA3AF',
        transform: [{ rotate: '90deg' }],
    },
    streetLabel2: {
        position: 'absolute',
        top: '15%',
        left: '25%',
        fontSize: 12,
        fontFamily: 'Sora_400Regular',
        color: '#9CA3AF',
    },
    streetLabel3: {
        position: 'absolute',
        top: '75%',
        right: '35%',
        fontSize: 12,
        fontFamily: 'Sora_400Regular',
        color: '#9CA3AF',
    },
    bottomInfoSection: {
        backgroundColor: 'white',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    deliveryTimeSection: {
        alignItems: 'center',
        marginBottom: 24,
    },
    timeLeft: {
        fontSize: 18,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
        marginBottom: 4,
    },
    deliveryAddress: {
        fontSize: 14,
        fontFamily: 'Sora_400Regular',
        color: '#9CA3AF',
    },
    progressContainer: {
        flexDirection: 'row',
        marginTop: 16,
        alignItems: 'center',
    },
    progressBarComplete: {
        height: 4,
        backgroundColor: '#4CAF50',
        borderRadius: 2,
    },
    progressBarIncomplete: {
        height: 4,
        backgroundColor: '#E0E0E0',
        borderRadius: 2,
    },
    progressBarSpacing: {
        marginLeft: 4,
    },
    statusSection: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F9F2ED',
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
    },
    statusIcon: {
        width: 40,
        height: 40,
        borderRadius: 8,
        backgroundColor: '#C67C4E',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    statusTextContainer: {
        flex: 1,
    },
    statusTitle: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
        marginBottom: 4,
    },
    statusDescription: {
        fontSize: 14,
        fontFamily: 'Sora_400Regular',
        color: '#9CA3AF',
        lineHeight: 20,
    },
    courierSection: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    courierInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    courierAvatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#E0E0E0',
        marginRight: 16,
        overflow: 'hidden',
    },
    courierImage: {
        width: '100%',
        height: '100%',
    },
    courierDetails: {
        flex: 1,
    },
    courierName: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
        marginBottom: 2,
    },
    courierTitle: {
        fontSize: 14,
        fontFamily: 'Sora_400Regular',
        color: '#9CA3AF',
    },
    callButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#C67C4E',
        alignItems: 'center',
        justifyContent: 'center',
    },
});