import { StyleSheet } from 'react-native';

export const orderStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: 'white',
    },
    container: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 16,
        backgroundColor: 'white',
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: '#F9F2ED',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 20,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
        textAlign: 'center',
        flex: 1,
        marginRight: 44,
    },
    scrollContainer: {
        flex: 1,
    },
    contentContainer: {
        paddingHorizontal: 24,
    },
    deliveryToggle: {
        flexDirection: 'row',
        backgroundColor: '#F9F2ED',
        borderRadius: 14,
        padding: 4,
        marginBottom: 24,
    },
    toggleButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 10,
        alignItems: 'center',
    },
    toggleButtonActive: {
        backgroundColor: '#C67C4E',
    },
    toggleButtonInactive: {
        backgroundColor: 'transparent',
    },
    toggleTextActive: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: 'white',
    },
    toggleTextInactive: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
    },
    addressSection: {
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
        marginBottom: 12,
    },
    addressContainer: {
        marginBottom: 16,
    },
    addressTitle: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
        marginBottom: 4,
    },
    addressText: {
        fontSize: 14,
        fontFamily: 'Sora_400Regular',
        color: '#9CA3AF',
        lineHeight: 20,
    },
    addressButtonsRow: {
        flexDirection: 'row',
    },
    addressButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E3E3E3',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginRight: 12,
    },
    addressButtonText: {
        fontSize: 14,
        fontFamily: 'Sora_400Regular',
        color: '#313131',
        marginLeft: 8,
    },
    orderItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#F0F0F0',
        borderRadius: 16,
        padding: 16,
        marginBottom: 24,
    },
    orderItemImage: {
        width: 60,
        height: 60,
        borderRadius: 12,
        backgroundColor: '#F9F2ED',
        marginRight: 16,
        overflow: 'hidden',
    },
    orderItemInfo: {
        flex: 1,
    },
    orderItemName: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
        marginBottom: 4,
    },
    orderItemDescription: {
        fontSize: 14,
        fontFamily: 'Sora_400Regular',
        color: '#9CA3AF',
    },
    quantityControls: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    quantityButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F9F2ED',
        alignItems: 'center',
        justifyContent: 'center',
    },
    quantityText: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
        marginHorizontal: 16,
    },
    discountSection: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        marginBottom: 24,
    },
    discountInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    discountIcon: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#C67C4E',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    discountText: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
    },
    paymentSummary: {
        marginBottom: 24,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    summaryLabel: {
        fontSize: 16,
        fontFamily: 'Sora_400Regular',
        color: '#313131',
    },
    summaryValue: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
    },
    deliveryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    deliveryPriceRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    originalPrice: {
        fontSize: 16,
        fontFamily: 'Sora_400Regular',
        color: '#9CA3AF',
        textDecorationLine: 'line-through',
        marginRight: 8,
    },
    paymentMethod: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#F9F2ED',
        borderRadius: 14,
        padding: 16,
        marginBottom: 24,
    },
    paymentInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    paymentIconContainer: {
        width: 24,
        height: 24,
        borderRadius: 4,
        backgroundColor: '#C67C4E',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    paymentMethodText: {
        fontSize: 16,
        fontFamily: 'Sora_600SemiBold',
        color: '#313131',
    },
    paymentAmount: {
        fontSize: 14,
        fontFamily: 'Sora_400Regular',
        color: '#C67C4E',
    },
    bottomSection: {
        paddingHorizontal: 24,
        paddingVertical: 20,
        backgroundColor: 'white',
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    orderButton: {
        backgroundColor: '#C67C4E',
        paddingVertical: 16,
        borderRadius: 16,
        alignItems: 'center',
    },
    orderButtonText: {
        color: 'white',
        fontSize: 18,
        fontFamily: 'Sora_600SemiBold',
    },
});